<div class="additional-cache-management">
    <h2 class="cs-csfeature__logo"><span><?= $block->escapeHtml(__('Flush cache by tag/URL')) ?></span></h2>
    <div style="clear: both;">
        <form action="<?= $this->getUrl('cache_clear/cache/clear') ?>">
            <?= $block->getChildHtml() ?>
        </form>
    </div>
    <a href="<?= $this->getUrl('cache_clear/cache/listing')?>">Cache cleanup listing</a>
</div>
